#!/bin/bash -e

# /usr/local/sbin/raspi-monitor
# Script to enable and disable the HDMI signal of the Raspberry PI
# Inspiration: http://www.raspberrypi.org/forums/viewtopic.php?t=16472&p=176258

CMD="$1"

function on {
	/opt/vc/bin/vcgencmd display_power 1
}

function off {
	/opt/vc/bin/vcgencmd display_power 0
}

function must_be_root {
    if [ $USER != root ]; then
        echo "ERROR: Script must be executed as root"
        exit 1
    fi
}

function main {
    must_be_root
    if [ "$CMD" == "on" ]; then
        on
    elif [ "$CMD" == "off" ]; then
        off
    else
        echo "Usage: $0 <on|off>"
        exit 1
    fi
    exit 0
}

main